apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: online-boutique
  source:
    repoURL: http://gitea:3000/root/repo-infra.git
    targetRevision: main
    path: manifests
    directory:
      include: redis-cart.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
